language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
os:
  - linux
  - osx
  - windows
install:
  - pip install -r requirements.txt
script:
  - bash test_examples.sh

branches:
  only:
    - master

git:
  depth: 1
