matrix:
  include:
    - name: "Python 3.6 - Linux"
      os: linux
      language: python
      python: "3.6"
      before_install:
        - python --version
    - name: "Python 3.7 - Linux"
      os: linux
      language: python
      python: "3.7"
      before_install:
        - python --version
    - name: "Python 3.8 - Linux"
      os: linux
      language: python
      python: "3.8"
      before_install:
        - python --version
      install:
        - echo "pass" # currently disabled; requirements are not needed for tests
      script:
        - python -m unittest discover -s tests -v
    - name: "Python 3.6 - macOS"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
      install:
        - pip3 install -r requirements.txt
      script:
        - python3 -m unittest discover -s tests -v
    - name: "Python 3.7 - macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - python3 --version
      install:
        - pip3 install -r requirements.txt
      script:
        - python3 -m unittest discover -s tests -v
    - name: "Python 3.8 - macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - eval "$(pyenv init -)"
        - pyenv install 3.8.1
        - pyenv shell 3.8.1
        - python --version
        - python -m pip install --upgrade pip
      install:
        - echo "pass"
      script:
        - python -m unittest discover -s tests -v
    - name: "Python 3.6 - Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
      install:
        - echo "pass" # currently disabled; requirements are not needed for tests
      script:
        - python -m unittest discover -s tests -v
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7 - Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      install:
        - echo "pass" # currently disabled; requirements are not needed for tests
      script:
        - python -m unittest discover -s tests -v
      env: PATH=/c/Python37:/c/Python36/Scripts:$PATH
    - name: "Python 3.8 - Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - python --version
        - python -m pip install --upgrade pip
      install:
        - echo "pass" # currently disabled; requirements are not needed for tests
      script:
        - python -m unittest discover -s tests -v
      env: PATH=/c/Python38:/c/Python36/Scripts:$PATH

install:
  - pip install -r requirements.txt

script:
  - bash test_examples.sh
  - mypy clippy ; flake8 clippy ; pylint clippy
  - coverage run -m unittest discover -s tests -v

after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  username: __token__
  password:
    secure: kdp4nqaUMDJs51eoC6cK0TQn8EZ5kRskjB6QKg/jfr3rfBKSIbU+dGv4hCPHWEDUtK2Tdsv8+bcgomSHWqf5Jy8AWyZxgX3ZI4yGfnG/voO37QxTQQOBQwniH5CfcueIb4PteMurlTgTaOUviFVLOji2mOnijEckuucsRvAep3VVjTG6tJ9VP5VodrR+UMhmJnf3s030tnxMiqksQmbPvQ7rH9+dtSfWhA95wdWCzDgl6UK4t7ge810gcBO0aoFC1q7fFBDdC3kqVfHlPlO8PuA7+nD32t5baxdzF8NN+A17iwgXPTAST2+OXWvEoPf/kd8mhQlwIYIrO/CFu9PwzA/r0XSFwGSkvdLmxqP/TucDIVpYVONvSMbKWRDhuVsVv7xHKPT9L6nEGayg9cjZXZGfxuWpl3snNErYZN9yzcvCfC9aORRzz00lhA5OqTeMelpSn3DpzcwGVP1d8RRX6hSXMucP3Ruc3AhHcqIbHi9XTp9uqouCbWkhMpfcxkHtSPbHoIROalSAyLTiu8nsokJSBNdwVZjB63MF2dCTzjfMiOu7Bg/t5sEymKVtN+2Z0c5r785+aYl89K/bs0buJENg7/bUycSa4Ferhp82OkDusrdBbo5BXqV65WY5iaGfRCQncG0ZQXCnAplisH5ZfZnJaVERQiixxtsAqD4XlBw=
  on:
    all_branches: true
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  cleanup: false

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

git:
  depth: 1
