language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
os:
  - linux
install:
  - pip install -r requirements.txt
script:
  - bash test_examples.sh
  - coverage run -m unittest discover -s tests -v
after_success:
  - codecov

branches:
  only:
    - master

git:
  depth: 1
