environment:
  matrix:
  - TOXENV: py38
  - TOXENV: py37
  - TOXENV: py36

build: false

install:
- SET PATH=%PYTHON%;%path%
- echo $PYTHON%
- echo %path%
- "python --version"
- pip install -r requirements.txt
- pip install tox

test_script:
- tox
