environment:
  matrix:
  - PYTHON: "C:\Python38"
  - PYTHON: "C:\Python37"
  - PYTHON: "C:\Python36"

build: false

install:
- SET PATH=%PYTHON%;%path%
- echo $PYTHON%
- echo %path%
- "python --version"
- pip install -r requirements.txt

test_script:
- python -m unittest discover -s tests -v
